[COR-139] GRPC Error Translation
beaconsoftwarellc/quimby pull request #10
Opened 2022-02-01 18:10 UTC by apynes

- Update dependencies to latest
- Added GRPC Errors to translate
- Switched tests to tabular pattern

2022-02-01 18:34 UTC, nmarie22 requested changes
Minor comment :+1:

2022-02-01 18:34 UTC, nmarie22 commented on error/model_test.go
> +	"gitlab.com/beacon-software/gadget/generator"
Gitlab import instead of github

2022-02-01 20:05 UTC, apynes commented on error/model_test.go
> +	"gitlab.com/beacon-software/gadget/generator"
argh, vs code is so freaking annoying with this. I don't know how it even knows about gitlab lol

2022-02-02 21:08 UTC, nmarie22 approved these changes

2022-02-02 22:22 UTC, merged