[UPGRADE-119] updating module and imports
beaconsoftwarellc/quimby pull request #16
Opened 2022-12-19 23:18 UTC by apynes

2022-12-19 23:23 UTC, webpro-jjaynes requested changes
I think you want to remove all the .vscode stuff from this check-in. It looks to be specific to your machine.

2022-12-19 23:26 UTC, apynes commented
> 

stupid vscode

2022-12-19 23:27 UTC, webpro-jjaynes approved these changes

2022-12-20 00:26 UTC, anthonyheidenreich approved these changes

2022-12-20 16:07 UTC, merged